[Service]
Host = "localhost"
Port = 49992
ConnectRetries = 3
Labels = []
OpenMsg = "device simple started"
MaxResultCount = 50000
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-int.log"
Level = "DEBUG"

# Pre-define Devices
[[DeviceList]]
  Name = "BigInt-Device01"
  Profile = "BigInt-Device"
  Description = "Big Integer Number Generator Device"
  Labels = [ "bigint", "test" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "bigint"
      Port = "300"
[[DeviceList]]
  Name = "SmallInt-Device01"
  Profile = "SmallInt-Device"
  Description = "Example of SmallInt Number Generator Device"
  Labels = [ "smallint" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "smallint"
      Port = "300"